export const refs = {
  gameScreen: document.getElementById('gameScreen'),
  statsScreen: document.getElementById('statsScreen'),

  inputCard: document.getElementById('inputCard'),
  timerCard: document.getElementById('timerCard'),
  setResultCard: document.getElementById('setResultCard'),
  frameResultCard: document.getElementById('frameResultCard'),
  actionsCard: document.getElementById('actionsCard'),

  player1Input: document.getElementById('player1Input'),
  player2Input: document.getElementById('player2Input'),
  player1Suggestions: document.getElementById('player1Suggestions'),
  player2Suggestions: document.getElementById('player2Suggestions'),
  player1LookupStatus: document.getElementById('player1LookupStatus'),
  player2LookupStatus: document.getElementById('player2LookupStatus'),
  playersError: document.getElementById('playersError'),
  gameError: document.getElementById('gameError'),
  typeError: document.getElementById('typeError'),
  frameTargetError: document.getElementById('frameTargetError'),
  timeTargetError: document.getElementById('timeTargetError'),

  gameSegments: document.getElementById('gameSegments'),
  typeSegments: document.getElementById('typeSegments'),
  frameTargetBlock: document.getElementById('frameTargetBlock'),
  frameTargetSegments: document.getElementById('frameTargetSegments'),
  timeTargetBlock: document.getElementById('timeTargetBlock'),
  timeTargetSegments: document.getElementById('timeTargetSegments'),

  repeatBtn: document.getElementById('repeatBtn'),
  resetInputsBtn: document.getElementById('resetInputsBtn'),

  timerDisplay: document.getElementById('timerDisplay'),
  timerModeSegments: document.getElementById('timerModeSegments'),
  startPauseBtn: document.getElementById('startPauseBtn'),
  stopBtn: document.getElementById('stopBtn'),
  resetTimeBtn: document.getElementById('resetTimeBtn'),
  timerHint: document.getElementById('timerHint'),
  timerStatusBadge: document.getElementById('timerStatusBadge'),

  setMetaText: document.getElementById('setMetaText'),
  setTimeBadge: document.getElementById('setTimeBadge'),
  setPlayer1Label: document.getElementById('setPlayer1Label'),
  setPlayer2Label: document.getElementById('setPlayer2Label'),
  setRowTime: document.getElementById('setRowTime'),
  setScore1: document.getElementById('setScore1'),
  setScore2: document.getElementById('setScore2'),
  setResultError: document.getElementById('setResultError'),
  abortSetBtn: document.getElementById('abortSetBtn'),
  saveSetBtn: document.getElementById('saveSetBtn'),

  frameCardTitle: document.getElementById('frameCardTitle'),
  frameMetaText: document.getElementById('frameMetaText'),
  currentPartyBadge: document.getElementById('currentPartyBadge'),
  framePlayer1Label: document.getElementById('framePlayer1Label'),
  framePlayer2Label: document.getElementById('framePlayer2Label'),
  frameRows: document.getElementById('frameRows'),
  frameResultError: document.getElementById('frameResultError'),
  winsSummary: document.getElementById('winsSummary'),
  ballsSummary: document.getElementById('ballsSummary'),
  targetSummary: document.getElementById('targetSummary'),
  frameStatusSummary: document.getElementById('frameStatusSummary'),
  nextPartyBtn: document.getElementById('nextPartyBtn'),
  abortFrameBtn: document.getElementById('abortFrameBtn'),
  saveFrameBtn: document.getElementById('saveFrameBtn'),

  newGameBtn: document.getElementById('newGameBtn'),
  goStatsBtn: document.getElementById('goStatsBtn'),

  backToGameBtn: document.getElementById('backToGameBtn'),
  clearStatsBtn: document.getElementById('clearStatsBtn'),
  statsModeSegments: document.getElementById('statsModeSegments'),
  historyStatsCard: document.getElementById('historyStatsCard'),
  databaseStatsCard: document.getElementById('databaseStatsCard'),
  statsCountBadge: document.getElementById('statsCountBadge'),
  statsEmptyState: document.getElementById('statsEmptyState'),
  statsList: document.getElementById('statsList'),
  databaseStatsBadge: document.getElementById('databaseStatsBadge'),
  statsReportSegments: document.getElementById('statsReportSegments'),
  matchesReportPanel: document.getElementById('matchesReportPanel'),
  playerReportPanel: document.getElementById('playerReportPanel'),
  leaderboardsReportPanel: document.getElementById('leaderboardsReportPanel'),
  statsPlayer1Input: document.getElementById('statsPlayer1Input'),
  statsPlayer2Input: document.getElementById('statsPlayer2Input'),
  statsPlayer1Suggestions: document.getElementById('statsPlayer1Suggestions'),
  statsPlayer2Suggestions: document.getElementById('statsPlayer2Suggestions'),
  statsPlayer1Status: document.getElementById('statsPlayer1Status'),
  statsPlayer2Status: document.getElementById('statsPlayer2Status'),
  statsPeriodSegments: document.getElementById('statsPeriodSegments'),
  loadMatchStatsBtn: document.getElementById('loadMatchStatsBtn'),
  matchStatsError: document.getElementById('matchStatsError'),
  matchStatsMetaText: document.getElementById('matchStatsMetaText'),
  matchStatsEmptyState: document.getElementById('matchStatsEmptyState'),
  matchStatsList: document.getElementById('matchStatsList'),
  matchStatsDetail: document.getElementById('matchStatsDetail'),

  toast: document.getElementById('toast'),
  confirmModal: document.getElementById('confirmModal'),
  modalTitle: document.getElementById('modalTitle'),
  modalText: document.getElementById('modalText'),
  modalCancelBtn: document.getElementById('modalCancelBtn'),
  modalConfirmBtn: document.getElementById('modalConfirmBtn')
};
